USE [master]
GO

/****** Object:  Database [TravelingAgencyDB]    Script Date: 2017-06-04 12:53:10 ******/
CREATE DATABASE [TravelingAgencyDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TravelingAgencyDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\TravelingAgencyDB.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'TravelingAgencyDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\TravelingAgencyDB_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [TravelingAgencyDB] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TravelingAgencyDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TravelingAgencyDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TravelingAgencyDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TravelingAgencyDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TravelingAgencyDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TravelingAgencyDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [TravelingAgencyDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TravelingAgencyDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TravelingAgencyDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TravelingAgencyDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TravelingAgencyDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TravelingAgencyDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TravelingAgencyDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TravelingAgencyDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TravelingAgencyDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TravelingAgencyDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TravelingAgencyDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TravelingAgencyDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TravelingAgencyDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TravelingAgencyDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TravelingAgencyDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TravelingAgencyDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TravelingAgencyDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TravelingAgencyDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [TravelingAgencyDB] SET  MULTI_USER 
GO

ALTER DATABASE [TravelingAgencyDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TravelingAgencyDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TravelingAgencyDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TravelingAgencyDB] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [TravelingAgencyDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TravelingAgencyDB] SET  READ_WRITE 
GO


